### ISSUE TITLE
Does not work as expected on Python 2.7.10

### ISSUE THREAD

**Issue by glenfant** [wbolster/qualname#1]
Hi,

I have the same result both with the latest release of qualname and the git head :

```
Python 2.7.10 (default, Sep 11 2015, 16:20:58) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.51)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from qualname import qualname
>>> import sys
>>> qualname(sys.path)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/glenfant/.virtualenvs/tmp-7b11cc4070ee454c/lib/python2.7/site-packages/qualname.py", line 51, in qualname
    return obj.__qualname__  # raises a sensible error
AttributeError: 'list' object has no attribute '__qualname__'
>>> from sys import modules
>>> qualname(modules)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/glenfant/.virtualenvs/tmp-7b11cc4070ee454c/lib/python2.7/site-packages/qualname.py", line 51, in qualname
    return obj.__qualname__  # raises a sensible error
AttributeError: 'dict' object has no attribute '__qualname__'
```

Am I missing something or is it a bug ?

**Comment by osdiab** [comment]
Also experiencing this :p

**Comment by osdiab** [comment]
Oh, it just doesn't work in the python REPL, because this library assumes the code is being run in a file. Tries to read source file, that errors and then it defaults to evaluating `__qualname__` without a check.

https://github.com/wbolster/qualname/blob/master/qualname.py#L48

**Comment by osdiab** [comment]
@wbolster plans to fix this?

**Comment by wbolster** [comment]
Qualname on py27 is a bit of hack since it REQUIRES reading source code (see implementation) because the needed info is not available from the interpreter.

Sure, I can make improvements that make it more robust. But for this particular case, what is the exact expected behaviour?

**Comment by wbolster** [comment]
See https://github.com/wbolster/qualname#how-does-it-work  for a rationale for the current implementation.

**Comment by wbolster** [comment]
Modules do not have a `__qualname__` attribute:

``` python
>>> from qualname import qualname
>>> import sys
>>> sys
<module 'sys' (built-in)>
>>> sys.__qualname__
Traceback (most recent call last):
  File "<ipython-input-5-262cc5ea0da1>", line 1, in <module>
    sys.__qualname__
AttributeError: 'module' object has no attribute '__qualname__'

>>> qualname(sys)
Traceback (most recent call last):
  File "<ipython-input-6-d008005da19b>", line 1, in <module>
    qualname(sys)
  File "/Users/wbolster/.virtualenvs/tmp-fb21cafaa4f02d6/lib/python3.4/site-packages/qualname.py", line 50, in qualname
    return obj.__qualname__  # raises a sensible error
AttributeError: 'module' object has no attribute '__qualname__'
```

`qualname(x)` is the same as `x.__qualname__`  on recent Python 3 versions. The whole point of the `qualname` library is that it is an emulation of that behaviour for older Python versions, particularly Python 2.7 which does not support this natively.

**Comment by wbolster** [comment]
Similarly, `dict` instances don't have a `__qualname__` attribute either:

```
>>> type(sys.modules)
<class 'dict'>
>>> sys.modules.__qualname__
Traceback (most recent call last):
  File "<ipython-input-8-0b705c1867bb>", line 1, in <module>
    sys.modules.__qualname__
AttributeError: 'dict' object has no attribute '__qualname__'
```

...so calling `qualname()` on it is expected to fail as well.

**Comment by wbolster** [comment]
This means that this is actually not a bug but expected behaviour.
