### ISSUE TITLE
Could be made to work without source files

### ISSUE THREAD

**Issue by wizzwizz4** [wbolster/qualname#6]
Correct me if I'm wrong, but as the versions of CPython before 3.3 are finite (excluding 2.7.x but that's not going to be a big enough change) couldn't you also traverse compiled bytecode in a similar way looking for the qualname?

If the CPython bytecode isn't available either (perhaps if it's not CPython) you could use `__module__` to find the module name, look that up in `sys.module` and then traverse that looking for the class. You could cut out most infinite depth things by not following attributes of objects where `getattr(type(obj), '__module__', None) in ('builtins',)` or something like that, and use a breadth-first search (or a search with a maximum depth) to work around that. (Or you could keep to standard `__qualname__` behaviour and limit it to classes, and cache what you've already seen to prevent infinite loops.)

Perhaps(?) preferably to that, you could use `gc.get_objects`, and find the parent of each object in the chain... but that way lies _madness_ and I don't think you need that if you're only dealing with standard `__qualname__`.

**Comment by wbolster** [comment]
hahahaha, i like the way you're thinking. :)

 this whole project started as a joke but apparently people use it. ;)

thanks for the awesome ideas on how to make this work in even weirder ways.

but the reality is that this is a fun hack, but it had its time. python 3 is the way forward.
